1. Tentukan determinan matriks berikut:

$$\displaystyle A = \left( \begin{array}{cc}
1 & 2 \\
3 & 4
\end{array}
\right)
$$

In [5]:
import numpy as np
from numpy.linalg import \
              matrix_rank

A = np.array([[1,2],[3,4]])

print('Rank:\n', matrix_rank(A))
y = np.array([[1], [2],])
A_y = np.concatenate((A, y), axis = 1)
print('Augmented matrix:\n', A_y)

Rank:
 2
Augmented matrix:
 [[1 2 1]
 [3 4 2]]


2. Tentukan invers Matriks Berikut:

$$\displaystyle B = \left( \begin{array}{cc}
10 & -22 \\
3 & 45
\end{array}
\right)
$$

In [6]:
import numpy as np

# Membuat matriks 2x2
M = np.array([[10, -22], [3, 45]])

# Menghitung invers matriks
inverse_of_M = np.linalg.inv(M)

print(inverse_of_M)

[[ 0.0872093   0.04263566]
 [-0.00581395  0.01937984]]


3. Tentukan apakah matriks berikut berkondisi buruk:
$$\displaystyle C = \left( \begin{array}{cc}
1 & 10^{-10} \\
10^{-10} & 1
\end{array}
\right)
$$



In [10]:
import numpy as np
from numpy.linalg import \
              cond

A = np.array([[1,10^-10],[10^-10,1]])
print('Condition number:\n', cond(A))


Condition number:
 1.6666666666666667


4. Tentukan apakah sistem persamaan linier berikut memiliki solusi. Jika ada, bagaimana solusinya?

$$\displaystyle A = \left( \begin{array}{cc}
1 & 2 \\
3 & 4
\end{array}
\right) $$


$$\displaystyle
b =  \left( \begin{array}{cc}
5 & 6
\end{array}
\right) \\
$$

In [11]:
from numpy.linalg import \
              matrix_rank
A = np.array([[1,2],
              [3,4]])
print('Rank:\n', matrix_rank(A))
b = np.array([[5], [6]])
A_b = np.concatenate((A, b), axis = 1)
print('Augmented matrix:\n', A_b)

Rank:
 2
Augmented matrix:
 [[1 2 5]
 [3 4 6]]


Tentukan dimensi ruang nol matriks berikut:


$$\displaystyle
C =
\left(
\begin{array}{ccc}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{array}
\right)
$$

In [12]:
# Tentukan matriks Anda (contoh matriks 3x3)
A = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Hitung peringkat matriks
rank = np.linalg.matrix_rank(A)

# Hitung dimensi ruang nol
num_columns = A.shape[1]
nullity = num_columns - rank

# Cetak hasil
print("Matriks:")
print(A)
print("Peringkat Matriks:", rank)
print("Dimensi Ruang Nol:", nullity)

Matriks:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Peringkat Matriks: 2
Dimensi Ruang Nol: 1
